[programs.localnet]
protocol_product = "mppFrYmM6A4Ud3AxRbGXsGisX1HUsbDfp1nrg9FQJEE"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"
